---
- name: Add linux-image-extra package (for AUFS)
  apt: name="linux-image-extra-{{ ansible_kernel }}"
    update_cache=yes
    cache_valid_time=86400

- name: Add linux-image-extra-virtual package (for AUFS)
  apt: name="linux-image-extra-virtual"
    update_cache=yes
    cache_valid_time=86400

- name: Add docker apt key
  apt_key:
     url=https://apt.dockerproject.org/gpg
     state=present
     id=2C52609D

- name: Add docker apt repository
  apt_repository:
     repo: 'deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main'
     update_cache: yes
     state: present

- name: Install docker engine
  apt:
    name="docker-engine{% if docker_version %}={{ docker_version }}*{% endif %}"
    update_cache=yes
    cache_valid_time=86400
- name: Add a docker group
  group:
    name=docker
    state=present
- name: Add user(s) to docker group
  user: 
      name={{ item }} 
      group=docker 
      state=present
  with_items: docker_users
  when: docker_users is defined
- name: Configure Docker 
  template: 
      src=default_docker.j2 
      dest=/etc/default/docker 
      mode=0644 
      owner=root 
      group=root
  notify: restart docker

- name: Ensuers docker config dir exists (root)
  file: path=/root/.docker state=directory
  when: docker_registries is defined

- name: Configure docker login (root)
  template:
      src=default_docker_config.json.j2
      dest=/root/.docker/config.json
      mode=0644
      owner=root
      group=root
  when: docker_registries is defined 

- name: Ensuers docker config dir exists
  file: path=/home/{{ item }}/.docker state=directory
  with_items: docker_users
  when: docker_users is defined

- name: Configure docker login
  template:
      src=default_docker_config.json.j2
      dest=/home/{{ item }}/.docker/config.json
      mode=0644
      owner={{ item }}
      group={{ item }}
  with_items: docker_users
  when: docker_registries is defined and docker_users is defined

- name: Configure logrotate for docker json log
  logrotate: name=docker-log path=/var/lib/docker/containers/*/*.log
  args:
    options:
      - daily
      - size 200M
      - rotate 3 
      - missingok
      - copytruncate
